### ISSUE TITLE
Feature: Tag people when they're let in a voice room

### ISSUE THREAD

**Issue by joshtrivedi** [Yes-Theory-Fam/yesbot-ts#1031]
Right now the person who knocks a voice room is mentioned in Room chat with message "Hey X, Y wants to join your room", and after Y is let in, It only says "Alright, I made room for them!" but Y has no idea if they've been let in (the previous version used to tell you X let you in, or X didn't respond.

**Comment by geisterfurz007** [comment]
Yeah, this should be possible! Currently we only defer the message of the result; instead we could immediately reply and use `followUp` to send another message that contains the ping once the result is available.

**Comment by joshtrivedi** [comment]
wow this is old
