### ISSUE TITLE
storing birthday in DB even after a user leaves and rejoins the server

### ISSUE THREAD

**Issue by findtravishere** [Yes-Theory-Fam/yesbot-ts#185]
maybe an issue for the backend(?) but groups are stored in the DB even after a user leaves but birthdays are reset back to unknown.

**Comment by geisterfurz007** [comment]
Yeah, this is indeed faulty but duplicate of #37

**Comment by findtravishere** [comment]
right 🤔 i knew i saw it somewhere before, mb
