### ISSUE TITLE
Add Tests to the bot

### ISSUE THREAD

**Issue by adrian-goe** [Yes-Theory-Fam/yesbot-ts#235]
Currently, there are no automatic tests.

To make sure that working code continues to work, tests should be added.

- [ ] add test framework (jest)
- [ ] write test for https://github.com/Yes-Theory-Fam/yesbot-ts/pull/242 after it is merged.

This will be the foundation, so all further refactoring can write test directly

**Comment by sklirg** [comment]
This should be pretty easy to convert to a testing framework when one is decided and set up: https://github.com/Yes-Theory-Fam/yesbot-ts/blob/master/src/programs/BirthdayManager.spec.ts

**Comment by adrian-goe** [comment]
@sklirg I assume so, but since we refactor more or less the whole code anyway, the test will rather not fit the new structure of the code itself.
But we will see how the code looks then.
Thanks for the hint 😊
