### ISSUE TITLE
Improve poll accuracy

### ISSUE THREAD

**Issue by mvarendorff** [Yes-Theory-Fam/yesbot-ts#250]
While emotes in polls are detected properly *most* of the time, there are some cases where emotes are missed. Since fixing missed emotes currently requires manual moderator action, it is desirable to avoid occurences like this.

In earlier attempts to pinpoint this issue, it seemed that there was massive inconsistency in the message content's causing the parsing to "fail" in certain instances with either emojis not getting picked up or emotes getting picked up which are then rejected by the Discord API.

If someone wants to work on this and would like to have logs of "broken" polls containing the charcodes of all detected emoji unicode characters, please let me know, then I can set up logging for that.

**Comment by geisterfurz007** [comment]
Haven't seen complaints on this for quite a long time. Closing.
