### ISSUE TITLE
new command for meta questions

### ISSUE THREAD

**Issue by adrian-goe** [Yes-Theory-Fam/yesbot-ts#252]
In some channels, meta questions like `is someone online and can help me?` or `who is from Spain?` come up more often.
Currently, moderators wrote a response and point out that this is not necessarily good. This is extra work that does not have to be. In addition, moderators do not always get that or must be specially pointed out.

To simplify this, a new command should be established. This command can be used from any Member.
A member A writes a meta question. Member B uses the reply function and the command `!meta`.
The bot replies to member A's message with the image and deletes the message from member B.

To avoid spam from the bot, there should be a channel cooldown. I would put at least 10 minutes here.
This should also work only once per marked message. Therefore, the ID of reported messages should be stored.

![image](https://user-images.githubusercontent.com/17064122/122255708-ae6e9680-cece-11eb-8c01-6f29a3995680.png)

**Comment by BlankWheein** [comment]
if you are tight on storage you can make the bot add a reaction to the message you reply to. This way the bot should just check if it reacted with an emoji to the message in question if so dont send the image.

**Comment by adrian-goe** [comment]
@BlankWheein this is a great idea. Thanks 😊
