### ISSUE TITLE
Cannot delete groups with at least one member in them

### ISSUE THREAD

**Issue by geisterfurz007** [Yes-Theory-Fam/yesbot-ts#313]
I think eventually this will have to be solved in [database](https://github.com/Yes-Theory-Fam/database) but can sit here for now.

To reproduce send the following messages in either bot-commands or permanent-testing:
```
!group create test
!group join test
!group delete test
```
This will throw a prisma error.

Once you leave the group, you can delete it.

This should be fixed.

**Comment by adrian-goe** [comment]
this https://github.com/prisma/prisma/issues/2810 will solved the issue with the group. its planned for 2.26 (current is 2.25)
Problem is, that the join table UserGroupMembersGroupMember still has the foreign key to the UserGroup. 
We can fix this manually by deleting all entries to the group in UserGroupMembersGroupMember before deleting it form UserGroup or wait, until the cascade feature comes. Probably next Tuesday

**Comment by adrian-goe** [comment]
Resolved with https://github.com/Yes-Theory-Fam/yesbot-ts/pull/352
