### ISSUE TITLE
@someone online conflict

### ISSUE THREAD

**Issue by hasanlatch007** [Yes-Theory-Fam/yesbot-ts#334]
`@someone online` is not working due to users joining with the discord tag `@someone`, all we need is to change its prefix (or ban them 👀)
For newcomers here is the file and line causing the issue :)
https://github.com/Yes-Theory-Fam/yesbot-ts/blob/21fa5e17efdb8e067ad855ff366eae8500846db8/src/events/message.ts#L108

**Comment by geisterfurz007** [comment]
This is avoided for now. I agree though that we should find a longer-lasting solution for this.

**Comment by geisterfurz007** [comment]
This hasn't been an issue since. Closing.

**Comment by geisterfurz007** [comment]
This is an issue again

**Comment by hasanlatch007** [comment]
> This is an issue again

Is defaulting to kicking the user still an option?

**Comment by geisterfurz007** [comment]
@afiveminutemeal has the last say on that 😄

**Comment by afiveminutemeal** [comment]
I kicked them because they had no interactions, however this is an annoying recurrence so I'd be fine with moving this to slash eventually.

**Comment by geisterfurz007** [comment]
I'll keep this open until slash commands are implemented then

**Comment by geisterfurz007** [comment]
I clicked the wrong button 🦥

**Comment by geisterfurz007** [comment]
Closed in #829
