### ISSUE TITLE
Bot incorrectly detects multiple flags

### ISSUE THREAD

**Issue by geisterfurz007** [Yes-Theory-Fam/yesbot-ts#382]
Sometimes when members drop their flag multiple times without spaces, the bot incorrectly registers multiple flags:

![grafik](https://user-images.githubusercontent.com/26303198/127673350-48151947-fa1a-4d46-9279-260338d767a2.png)

Cause of this is the detection of flags which is done by a simple string lookup. In the case in the image above, the indicators are `INININ` which also makes the flag of Nicaragua (NI) match.

**Comment by hasanlatch007** [comment]
Since we know the indicators for a flag is two letters, maybe split every 2 letters? Compare them if they are the same just go through if not then reply. Not sure if its the most creative way to deal with it, tried implementing it but failed miserably :')
