### ISSUE TITLE
Create a new form of ticket for the traveling-together channel

### ISSUE THREAD

**Issue by mvarendorff** [Yes-Theory-Fam/yesbot-ts#489]
Let's be honest: #traveling-together is a mess at the moment; it was suggested that we use the recently refactored ticket system to have travel request sent in a more streamlined manner and to declutter the channel which is currently full of both people's requests *and* the Support's replication of it.

That should help reduce the amount of chaos in the channel and help Supports to keep track of what already has a thread and what doesn't until a neater solution is finally ready for launch.

### Update

After a recent mod meeting, this has been extended:

- Bot command `!travel` that collects the data for the current "form"
    - Requires "Seek Discomfort" (sends error message when missing role)
    - Puts it into the format currently used in traveling-together
    - Puts it up for Supports to approve it (Member shall have patience)
    - If approved sends in traveling-together (Support creates a thread until YesBot is moved to Discord.js v13)
    - If declined:
        - Message is sent to ticket channel
        - Member has to redo it again with the changes asked by the Support

**Comment by hasanlatch007** [comment]
I do have an idea but it requires Discord.js 13, maybe use a form that asks for all the relative information and make the bot create the thread himself?

**Comment by geisterfurz007** [comment]
That is one of the options that was discussed in a mod call recently; either try to use forms (which might be a mess because they don't support free text yet so that would still have to be done through sending messages) or embed it into the website once that is done.
