### ISSUE TITLE
dailychallenge ping doesn't ping group

### ISSUE THREAD

**Issue by geisterfurz007** [Yes-Theory-Fam/yesbot-ts#551]
The dailychallenge ping as well as the yestheoryuploads ping from the bot don't appear to actually cause a ping since sunday requiring a manual one instead:

![grafik](https://user-images.githubusercontent.com/26303198/138053794-2135d8ab-7f6a-4e84-a8e3-a17b04691de6.png)

There are no visible errors in the log. This needs investigation and fix.

**Comment by joshtrivedi** [comment]
I think it has to do something with GroupPingSetting, since when a member pings the group it tags, but not when yes bot does
![image](https://user-images.githubusercontent.com/50212531/155967545-c9fd772a-8eb9-48a5-95d3-f0cf8e7de049.png)

**Comment by geisterfurz007** [comment]
In that case, the behaviour should be consistent which it isn't; take today's daily challenge for example where everything worked as expected: 

![grafik](https://user-images.githubusercontent.com/26303198/155975547-883c4e2c-cc44-4b2d-bd9a-23a122e2f92e.png)

I'm gonna release an update to YesBot later which will include #664; @hasanlatch007 had done some investigation in the past and it seemed that some events were just being dropped by discord.js so sending everything in one message could be an option.  
If that doesn't turn out to be a solution, we can ramp up the logging, possibly even within discord.js to see if anything messes up in there but fingers crossed that's not needed!

**Comment by hasanlatch007** [comment]
> I think it has to do something with GroupPingSetting, since when a member pings the group it tags, but not when yes bot does ![image](https://user-images.githubusercontent.com/50212531/155967545-c9fd772a-8eb9-48a5-95d3-f0cf8e7de049.png)

What Michel said, also if you try to ping a group that has the `GroupPingSetting` set it would result in an error, saying `This group is only pingable by {SETTING}`, for now, we're testing sending everything in one message.

**Comment by joshtrivedi** [comment]
> > I think it has to do something with GroupPingSetting, since when a member pings the group it tags, but not when yes bot does ![image](https://user-images.githubusercontent.com/50212531/155967545-c9fd772a-8eb9-48a5-95d3-f0cf8e7de049.png)
> 
> What Michel said, also if you try to ping a group that has the `GroupPingSetting` set it would result in an error, saying `This group is only pingable by {SETTING}`, for now, we're testing sending everything in one message.

So by that you mean including the group tag in the embed or sending the whole thing as a message.

**Comment by geisterfurz007** [comment]
> So by that you mean including the group tag in the embed or sending the whole thing as a message.

Currently two messages are sent; the first message is the group ping, the second message is the embed; they can be combined into a single one containing both the plain text group ping as well as the embed; that seemed to have worked today at least!

**Comment by geisterfurz007** [comment]
Aaand it didn't for YesTheoryUploads. So this will require a good bunch of logging along the expected path of the message event to see where it is dropped.

**Comment by joshtrivedi** [comment]
I'll take a look at it tonight, what branch is it being worked on

**Comment by geisterfurz007** [comment]
There is no branch for adding logging at the moment; the code that's currently live is failing, so you can create a branch from master.

**Comment by geisterfurz007** [comment]
Closed with #708
