### ISSUE TITLE
Remove all !timeout functionality

### ISSUE THREAD

**Issue by geisterfurz007** [Yes-Theory-Fam/yesbot-ts#624]
Discord has recently released the [Time Out functionality](https://support.discord.com/hc/de/articles/4413305239191) as moderative tool. It replicates the behaviour of our current toolset so `!timeout` and `!timeoutTimer` are not needed anymore.

This should be coordinated with at least one Support member to ensure permissions are set correctly for Companions and Support and to ensure that the feature is actually enabled on the server (and not just announced).

**Comment by hasanlatch007** [comment]
For now this is still in the talk with Josh, since he was kind of against it because it cannot have indefinite timeout
I was thinking of removing the timeout role completely. 
We could still get rid of `timeoutTimer` since the new feature does exactly as the command.

**Comment by hasanlatch007** [comment]
@geisterfurz007 What's the update on this? Are we keeping the command?

**Comment by geisterfurz007** [comment]
Afaik, we wanted to keep the role and thus the command until there is a list of members on time out (similar to the list of banned members). But eventually that's @afiveminutemeal's decision, I believe.

**Comment by hasanlatch007** [comment]
> Afaik, we wanted to keep the role and thus the command until there is a list of members on time out (similar to the list of banned members). But eventually that's @afiveminutemeal's decision, I believe.

Ok, I'll let you decide if you want to close this issue.
