### ISSUE TITLE
Use strict null checks

### ISSUE THREAD

**Issue by geisterfurz007** [Yes-Theory-Fam/yesbot-ts#625]
Just to note: This is going to be a pest to work through but I genuinely believe it's necessary at the scale YesBot is at now.

https://github.com/Yes-Theory-Fam/yesbot-ts/blob/36dac2af9813c0863f4c789461fe4acf5b2a6a85/tsconfig.json#L14

The tsconfig defines `"strictNullChecks": false` which causes an absurd amount of potential runtime errors to not get picked up by the type checker. To fix this, delete that line from the tsconfig (`strictNullChecks` is enabled through `strict` in the line above) and go on a hunt for null/undefined errors and address them.

**Comment by sklirg** [comment]
Suggestion: To not have to make the PR being gigantic and possibly have conflicts with other code changes, follow the incremental plan that VSCode used (or a similar approach) when they did the same for their codebase. https://code.visualstudio.com/blogs/2019/05/23/strict-null#_coming-up-with-an-incremental-plan

The whole article is a nice read. :-)
