### ISSUE TITLE
Upgrade Node in GitHub Workflows

### ISSUE THREAD

**Issue by geisterfurz007** [Yes-Theory-Fam/yesbot-ts#644]
While our Docker container is on Node 16.13, the Actions still run under Node 16.6. This should be updated!

The `.github/workflows` directory contains four files for our actions. This issue concerns only `build.yml`, `test.yml` and `linting.yml` which all define Node 16.6 as their environment. Take this instance for example:

https://github.com/Yes-Theory-Fam/yesbot-ts/blob/d85626b90217d8018da5ac3a7565c8ce8e529a9a/.github/workflows/build.yml#L16

This should be updated to Node 16.13 across those three files.

**Comment by RishiKumarRay** [comment]
@geisterfurz007 please review pr

**Comment by RishiKumarRay** [comment]
@geisterfurz007 thanks for approving , this was quite easy, if you are planning on anything using github actions please let me know , i would love to contribute

**Comment by geisterfurz007** [comment]
Thanks, I appreciate it! I don't think there is much planned at the moment but I will keep you in mind should anything come up in the future!
