### ISSUE TITLE
group pings don't respect active chats

### ISSUE THREAD

**Issue by geisterfurz007** [Yes-Theory-Fam/yesbot-ts#688]
Group pings allow a setting to reject pinging members when chat is active. This setting is not honored anymore which should be fixed.

**Comment by hasanlatch007** [comment]
Josh ran the command `!group changeDeadtime HydroHomies 60` and it fixed the issue, somehow the time was set back to 0..?

**Comment by geisterfurz007** [comment]
> somehow the time was set back to 0

Turns out this likely happened due to a data loss in September last year with data restored from July which is when this was released. I assume the backup I used to restore the bot in September was created just before migrating the database to support the feature which would explain the default value even for hydrohomies.

Closing this, because it's not actionable anymore to my knowledge.
