### ISSUE TITLE
enhancement: Add Buttons instead of Reactions in Pagination based Embeds 

### ISSUE THREAD

**Issue by joshtrivedi** [Yes-Theory-Fam/yesbot-ts#694]
![image](https://user-images.githubusercontent.com/50212531/163381796-aa0c6d6d-85f1-4235-bd22-b5b007bac597.png)
the way the embeds are set up right now is the bot adds a reaction, waits for another reaction from the user, checks if the user who made the reaction is the same as the user who used the command, remove the reaction, flip the page.
this can be done easily using the ActionRows and Buttons since the v13 Collector looks more reliable.

**Comment by geisterfurz007** [comment]
Closed in #873
