### ISSUE TITLE
Approve shoutout tickets

### ISSUE THREAD

**Issue by geisterfurz007** [Yes-Theory-Fam/yesbot-ts#720]
Currently the process to approve a shoutout process looks like this:

1. Copy the user's name / tag
2. Go to #shoutout settings
3. Create new permissions for that user
4. Send message in the ticket channel letting them know that they can post now
5. Wait for them to post
6. Remove permissions from #shoutout
7. Close the ticket

This could possibly be automated with some sort of approval command that handles at least steps 1 through 4. In a later stage this might be extended to also cover 5-7 but I am not sure yet.

**Comment by christolis** [comment]
Has anybody worked on this? Also, I recommend setting a default 24-hour time space before the user has their permission automatically revoked for safety reasons.
