### ISSUE TITLE
Make private voice channels chat private on vc creation

### ISSUE THREAD

**Issue by hasanlatch007** [Yes-Theory-Fam/yesbot-ts#724]
Right now the VC channels that are created by users are accessible to the public, this should be fixed to make it private to those in the room.

**Comment by hasanlatch007** [comment]
After further investigation, I realized I could stop users from outside the channel don't send messages, but not viewing them.
@geisterfurz007 At this point it's up to you if I should continue with this or not if it's worth it.

**Comment by geisterfurz007** [comment]
Probably not, I think; I am not sure they are used a lot anyway. Should this ever come up, we can still give it a shot but if that's a thing that Discord enforces, I don't see much point trying to work around that without demand for it.
