### ISSUE TITLE
Voice Up doesn't up more than voiceLimit + 1

### ISSUE THREAD

**Issue by hasanlatch007** [Yes-Theory-Fam/yesbot-ts#728]
I'm not the sharpest tool in the shed for not thinking about this
![image](https://user-images.githubusercontent.com/6049462/172727505-622f28e6-3ba8-43ca-b3ed-3bb44cc198a4.png)

**Comment by jitsedesmet** [comment]
I'm interested in taking this as a first issue if it isn't a high prio issue :)

**Comment by hasanlatch007** [comment]
> I'm interested in taking this as a first issue if it isn't a high prio issue :)

It is more of an annoying bug than anything and has a work-around for the current moment so take your time :)

**Comment by geisterfurz007** [comment]
That we can do for sure! I have assigned you as well :) If you have any questions or face troubles setting up the bot for yourself, don't hesitate to reach out to Hasan or me!

**Comment by geisterfurz007** [comment]
Closed with #873
